import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import CTA from "@/components/CTA";
import Showreel, { ShowreelItem } from "@/components/Showreel";

export const metadata = {
  title: "Showreel — Axolotl Army",
  description:
    "Examples of AI-generated videos produced by the Axolotl Army platform — characters, product demos, short-form social clips, cinematic openers.",
};

/**
 * Placeholder showreel — reuses the existing character and animation clips
 * as stand-ins for now. Swap these entries as new showreel content lands
 * in /public/videos/.
 */
const items: ShowreelItem[] = [
  {
    src: "/videos/axo-prime.mp4",
    title: "Character short — Axo Prime",
    caption: "8-second TikTok-ready clip with brand-anchored character.",
    tag: "8s",
    size: "tall",
  },
  {
    src: "/videos/axo-neon.mp4",
    title: "High-energy promo — Axo Flash",
    caption: "Scroll-stopping hook generated by the Hype Creator agent.",
    tag: "8s",
  },
  {
    src: "/videos/axo-shadow.mp4",
    title: "Data-driven spot — Axo Edge",
    caption: "Analytics-backed script + cinematic lighting.",
    tag: "8s",
  },
  {
    src: "/videos/axolotl-river.mp4",
    title: "Cinematic establisher",
    caption: "Wide-angle hero shot generated with Veo3.",
    tag: "30s",
    size: "wide",
  },
  {
    src: "/videos/axo-bloom.mp4",
    title: "Artistic — Axo Dream",
    caption: "Story-driven output from the Creative agent.",
    tag: "8s",
  },
  {
    src: "/videos/scroll-sequence.mp4",
    title: "360° product rotation",
    caption: "Character spin for a product merch campaign.",
    tag: "3s",
  },
];

export default function ShowreelPage() {
  return (
    <>
      <Nav />
      <main>
        <section className="pt-32 pb-12 px-6">
          <div className="max-w-[1400px] mx-auto">
            <p className="text-accent font-mono text-sm tracking-wider uppercase mb-4">
              What We Build
            </p>
            <h1 className="text-4xl md:text-6xl tracking-tighter leading-none font-bold text-foreground mb-6 max-w-3xl">
              A showreel of what the platform generates
            </h1>
            <p className="text-muted text-lg leading-relaxed max-w-[60ch]">
              Every clip below came out of our 40-agent pipeline — scripted,
              generated, QA'd by the Creative Director agent, and
              platform-optimized for TikTok, Instagram, YouTube, or X.
              Updated as we ship new styles.
            </p>
          </div>
        </section>

        <section className="pb-24 px-6">
          <div className="max-w-[1400px] mx-auto">
            <Showreel items={items} columns={3} />
          </div>
        </section>

        <CTA />
      </main>
      <Footer />
    </>
  );
}
